### ISSUE TITLE
Hi I am having a problem with IE9

### ISSUE THREAD

**Issue by johndavedecano** [cbavota/Gridiculous#1]
I am using 960 for my container and 3 c4 columns. When i tested in IE9, the third column went down to the new line. Please let me know if you have fix for this issue.

Thanks,Dave

**Comment by cbavota** [comment]
Hey Dave,

Setting up a dev environment for IE9 on my Mac. I'll get back to you as soon as I test and figure out the issue.

**Comment by johndavedecano** [comment]
Hi Chris,

Thank you very much in advance.

Dave,

**Comment by isotrope** [comment]
Hi Dave,
Do you have a live demo/jsfiddle of your issue?
If you check out the http://gridiculo.us/ page, there actually is a 3x c4 example:

``` html

<div class="row">
            <div class="c4"><span class="demo">4 Columns</span></div>
            <div class="c4"><span class="demo">4 Columns</span></div>
            <div class="c4 end"><span class="demo">4 Columns</span></div>
        </div>
```

It shows up fine in IE9.
Cheers,
iso

PS. Don't forget to add the <em>.end</em> class to your last column.

**Comment by johndavedecano** [comment]
Resolved! THanks
