### ISSUE TITLE
Any reason not to upgrade to normalize.css 2.0.1?

### ISSUE THREAD

**Issue by ajk1982** [cbavota/Gridiculous#2]
Great system! Any reason it couldn't be updated to use normalise.css 2.0.1?

**Comment by cbavota** [comment]
No reason whatsoever. Just haven't had a chance to implement it and play around with it. Will do shortly, though. Thanks.

**Comment by ajk1982** [comment]
Awesome. This is really a great grid system.

**Comment by cbavota** [comment]
If you use WordPress I've put together a theme: http://wordpress.org/extend/themes/gridiculous

**Comment by ajk1982** [comment]
I used to be a WordPress fan but now I prefer http://habariproject.org/en/ or http://chyrp.net. There aren't many themes for them ;-)

**Comment by cbavota** [comment]
Just updated Normalize.
